### PR TITLE
Sanitize widgets

### PR DESCRIPTION
**Pull request by nitriques**
See https://github.com/symphonycms/symphony-2/pull/2781

### CODE REVIEW

**Review by michael-e — COMMENTED** [review]
You forgot to change Symphony compatibility [as discussed](https://github.com/symphonycms/symphony-2/pull/2781#issuecomment-355381903). Version `1.2.0` should have `max="2.7.0"`, the new extension version (ideally `2.0.0`?) should have `min="2.7.1"`.

**Comment by nitriques** [comment]
Yeah, but from what I've tested, it still works with the old code ... Should we really take that extra precaution ?

**Comment by michael-e** [comment]
Let's continue [in the Symphony thread](https://github.com/symphonycms/symphony-2/pull/2781#issuecomment-358140487).

**Comment by michael-e** [comment]
See https://github.com/symphonycms/symphony-2/pull/2781#issuecomment-358143265

**Review by michael-e — APPROVED** [review]

**Pull request merged**
